// "use client";
// 
// import { useEffect } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import InstallBootstrap from './components/InstallBootstrap';
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{


  return (
    <html dir="rtl" lang="fa">
      <body className={inter.className}>
      <InstallBootstrap />
        {children}
        </body>
    </html>
  );
};
